"use server";

import { GoogleGenAI } from "@google/genai";

const TEXT_MODEL = 'gemini-2.0-flash-exp';
const IMAGE_MODEL = 'gemini-2.5-flash-image';

const getAI = (userKey?: string) => {
    const key = userKey;
    if (!key) {
        throw new Error("API Key is missing. Please provide it in Settings.");
    }
    return new GoogleGenAI({ apiKey: key });
};

export const checkConfigurationAction = async (apiKey?: string): Promise<{ status: 'ok' | 'error', message: string }> => {
    try {
        const ai = getAI(apiKey);
        // Simple test call
        await ai.models.generateContent({
            model: TEXT_MODEL,
            contents: [{ role: 'user', parts: [{ text: 'Test' }] }],
        });
        return { status: 'ok', message: "Google GenAI is configured and working." };
    } catch (error) {
        return { status: 'error', message: `API Connection Failed: ${error instanceof Error ? error.message : String(error)}` };
    }
};

const fileToGenerativePart = async (file: File) => {
  const arrayBuffer = await file.arrayBuffer();
  const base64 = Buffer.from(arrayBuffer).toString('base64');
  return {
    inlineData: { data: base64, mimeType: file.type },
  };
};

const extractInlineImage = (response: any): string => {
    const imagePart = response.candidates?.[0]?.content?.parts?.find((p: any) => p.inlineData?.data);
    
    if (!imagePart?.inlineData?.data) {
        throw new Error("No image generated by Gemini.");
    }
    
    return imagePart.inlineData.data;
};



export const enhancePromptAction = async (prompt: string, apiKey?: string): Promise<string> => {
    const systemInstruction = `You are an expert creative director specializing in visual content. Your task is to enhance the following user prompt to generate a more detailed and visually rich image. Do not generate the image description itself, but rather a better prompt for an AI image generator.

Rules:
- Add specific details about style, mood, and composition.
- Include technical photography or art terms where relevant (e.g., 'shot on 35mm film', 'depth of field', 'chiaroscuro lighting').
- Specify lighting, colors, and atmosphere.
- Make the description more vivid and detailed.
- Keep the core subject of the original prompt.
- The output must be only the enhanced prompt, with no additional text, titles, or explanations.`;

    const ai = getAI(apiKey);
    const response = await ai.models.generateContent({
        model: TEXT_MODEL,
        contents: [{ role: 'user', parts: [{ text: `Original Prompt: "${prompt}"` }] }],
        config: {
            systemInstruction,
            temperature: 0.8,
        },
    });

    const text = response.candidates?.[0]?.content?.parts?.[0]?.text;
    return text?.trim() || "";
};

export const stageRealEstateImageAction = async (formData: FormData): Promise<string> => {
    const imageFile = formData.get('image') as File;
    const style = formData.get('style') as string;
    const apiKey = formData.get('apiKey') as string | undefined;

    if (!imageFile || !style) throw new Error("Missing image or style");

    const imagePart = await fileToGenerativePart(imageFile);
    
    const prompt = `Virtually stage this empty or outdated room in a "${style}" style. Photorealistic. Keep the structural elements (walls, windows, doors) exactly the same, only add furniture and decor.`;
    
    try {
        const ai = getAI(apiKey);
        const response = await ai.models.generateContent({
            model: IMAGE_MODEL,
            contents: [
                { role: 'user', parts: [imagePart, { text: prompt }] }
            ],
            config: {
                responseModalities: ['IMAGE'],
            }
        });

        return extractInlineImage(response);
    } catch (e) {
        console.error("Gemini generation failed:", e);
        throw new Error(`Failed to generate image with Gemini: ${e instanceof Error ? e.message : String(e)}`);
    }
};

export const generateVirtualTryOnImageAction = async (formData: FormData): Promise<string> => {
    const imageFile = formData.get('image') as File;
    const style = formData.get('style') as string;
    const apiKey = formData.get('apiKey') as string | undefined;

    if (!imageFile || !style) throw new Error("Missing image or style");

    const imagePart = await fileToGenerativePart(imageFile);
    const prompt = `Replace the clothing with a ${style} outfit. Do not change the face or body pose. Photorealistic fashion photography.`;
    
    try {
        const ai = getAI(apiKey);
        const response = await ai.models.generateContent({
            model: IMAGE_MODEL,
            contents: [
                { role: 'user', parts: [imagePart, { text: prompt }] }
            ],
            config: {
                responseModalities: ['IMAGE'],
            }
        });

        return extractInlineImage(response);
    } catch (e) {
        console.error("Gemini generation failed:", e);
        throw new Error(`Failed to generate image with Gemini: ${e instanceof Error ? e.message : String(e)}`);
    }
};

export const generateFoodImageAction = async (prompt: string, style: string, apiKey?: string): Promise<string> => {
    const fullPrompt = `A photorealistic image of ${prompt}, in a ${style} style. The food should look delicious and appealing. High resolution food photography.`;

    try {
        const ai = getAI(apiKey);
        const response = await ai.models.generateContent({
            model: IMAGE_MODEL,
            contents: [{ role: 'user', parts: [{ text: fullPrompt }] }],
            config: {
                responseModalities: ['IMAGE'],
            }
        });

        return extractInlineImage(response);
    } catch (e) {
        console.error("Gemini generation failed:", e);
        throw new Error(`Failed to generate image with Gemini: ${e instanceof Error ? e.message : String(e)}`);
    }
};

const BASE_AD_PROMPT = `You are a professional ad designer. Your goal is to create a high-end, photorealistic product advertisement.

STRUCTURE OF THE PROMPT:
1. SUBJECT: The product from the input image.
2. SETTING: The environment or background described in the style.
3. COMPOSITION: The camera angle, framing, and depth.
4. LIGHTING: The specific lighting conditions and mood.
5. STYLE: The overall aesthetic and artistic direction.
6. TEXT: The headline and subtext, integrated into the scene (behind the product, on a wall, etc.).

CRITICAL RULES (VERY IMPORTANT):
- The product must be the central focus.
- TEXT PLACEMENT IS CRITICAL:
  - The text must be a physical part of the scene (e.g., neon sign on the back wall, 3D letters standing on the floor, painted on the background surface).
  - The text must be placed strictly BEHIND the product in 3D space.
  - The product should partially occlude the text where they overlap in screen space.
  - The text must NEVER sit on top of or in front of the product.
  - Do NOT create flat, 2D overlay text, banners, UI labels, or captions.
- If you are unsure, prefer to keep the text smaller and further back rather than closer to the viewer.
- Use specific, descriptive language (e.g., "golden hour backlighting" instead of "nice light").
- Do not invent or change real brand names or logos other than what is already present on the product in the input image.
- Ensure the text is legible but fully integrated into the environment as a physical object, not an overlay.`;

const AD_STYLE_PROMPTS: Record<string, string> = {
    'Bold Modern': `STYLE: BOLD MODERN (Sprite-Style)
- Setting: A glossy, high-contrast studio environment or a blurred vibrant cityscape.
- Composition: Close-up, slightly low-angle, centered.
- Lighting: Bright, crisp natural daylight or high-key studio lighting.
- Aesthetic: Clean, fresh, energetic, punchy colors.
- Text Integration: Large, bold 3D letters placed physically BEHIND the subject. The text should look like a studio prop or background structure.`,

    'Dark Luxe': `STYLE: DARK PREMIUM LUXE (Coca-Cola Style)
- Setting: A dark, reflective surface with a moody, cinematic background.
- Composition: Centered close-up, dramatic low-angle.
- Lighting: Moody, rich warm highlights, deep shadows, rim lighting.
- Aesthetic: Opulent, sophisticated, black-and-gold color scheme.
- Text Integration: Glowing neon or metallic letters mounted on the back wall, softly illuminated. The text is part of the background set.`,

    'Vintage': `STYLE: VINTAGE POSTER / ILLUSTRATED
- Setting: A hand-drawn pastel background or a textured paper surface.
- Composition: Front and center, poster-style framing.
- Lighting: Soft, warm, nostalgic glow.
- Aesthetic: Retro, 1950s advertisement, halftone shading, faded colors.
- Text Integration: The text is screen-printed directly onto the background texture. It should look like ink on paper, behind the product.`,

    'Scandinavian': `STYLE: MINIMAL SCANDINAVIAN
- Setting: A clean white tabletop or a light wood surface with negative space.
- Composition: Straight-on, simple, balanced, 1:1 ratio.
- Lighting: Soft, natural window light, gentle shadows.
- Aesthetic: Clean, calm, airy, premium product design.
- Text Integration: Thin, matte 3D letters mounted on the wall behind the product. Very subtle shadows cast by the text.`,

    'Pop Art': `STYLE: FUNKY POP ART
- Setting: A bold background of colorful comic-style shapes and patterns.
- Composition: Mid-frame portrait, slightly tilted angle.
- Lighting: Flat, bright, high-contrast.
- Aesthetic: Vibrant, loud, graphic, comic-book style.
- Text Integration: Large comic-book style letters painted onto the background wall. The text is part of the mural behind the product.`,

    'Neon Glow': `STYLE: FUTURISTIC NEON
- Setting: A dark reflective surface with a blurred cyberpunk cityscape at night.
- Composition: Low-angle, dynamic framing.
- Lighting: Vibrant neon blue and pink backlighting, high contrast.
- Aesthetic: Sci-fi, cyberpunk, electric, futuristic.
- Text Integration: Real neon glass tubes forming the words, suspended in the air behind the product.`,

    'Organic': `STYLE: PREMIUM ORGANIC
- Setting: A rough wood slab or stone surface surrounded by greenery/nature.
- Composition: Centered close-up, soft focus on background plants.
- Lighting: Warm natural light filtering through leaves (dappled light).
- Aesthetic: Earthy, natural, eco-friendly, calming.
- Text Integration: Carved wooden letters or engraved stone text placed in the background. The text feels natural and tactile.`
};

export const generateBeautyAdImageAction = async (formData: FormData): Promise<string> => {
    const imageFile = formData.get('image') as File;
    const prompt = formData.get('prompt') as string;
    const style = formData.get('style') as string;
    const adText = formData.get('adText') as string;
    const apiKey = formData.get('apiKey') as string | undefined;

    if (!imageFile || !prompt || !style) throw new Error("Missing image, prompt or style");

    const imagePart = await fileToGenerativePart(imageFile);
    
    if (!AD_STYLE_PROMPTS[style]) {
        console.warn(`Unknown ad style "${style}", falling back to Bold Modern`);
    }
    const stylePrompt = AD_STYLE_PROMPTS[style] || AD_STYLE_PROMPTS['Bold Modern'];

    const fullPrompt = `
    ${BASE_AD_PROMPT}

    ---
    INPUT CONTEXT:
    User Request: "${prompt}"
    Specific Text to Include: "${adText || 'Create a catchy headline suitable for the product'}"
    
    ---
    STYLE DEFINITION:
    ${stylePrompt}
    
    ---
    INSTRUCTIONS:
    Combine the INPUT CONTEXT with the STYLE DEFINITION to generate the final image.
    CRITICAL: The text MUST be rendered as a physical object in the scene (e.g. a neon sign, a poster on the wall, or 3D letters standing on the floor). It must be BEHIND the product. Do not overlay text digitally.
    Place the text strictly BEHIND the product, never overlapping.
    `;

    try {
        const ai = getAI(apiKey);
        const response = await ai.models.generateContent({
            model: IMAGE_MODEL,
            contents: [
                { role: 'user', parts: [imagePart, { text: fullPrompt }] }
            ],
            config: {
                responseModalities: ['IMAGE'],
            }
        });

        return extractInlineImage(response);
    } catch (e) {
        console.error("Gemini generation failed:", e);
        throw new Error(`Failed to generate image with Gemini: ${e instanceof Error ? e.message : String(e)}`);
    }
};

export const generateBeautyAdImageExperimentalAction = async (formData: FormData): Promise<{ image: string; headline: string; tagline: string }> => {
    const imageFile = formData.get('image') as File;
    const prompt = formData.get('prompt') as string;
    const style = formData.get('style') as string;
    const adText = formData.get('adText') as string;
    const apiKey = formData.get('apiKey') as string | undefined;

    if (!imageFile || !prompt || !style) throw new Error("Missing image, prompt or style");

    // 1. Analyze image and generate copy (Headline/Tagline) only
    const imagePart = await fileToGenerativePart(imageFile);
    
    const analysisPrompt = `
    Analyze this product image and the user's request.
    User Request: Place this product in a "${style}" scene. Context: ${prompt}.
    ${adText ? `Requirement: The image MUST include the text "${adText}" visible in the scene.` : ''}

    Tasks:
    1. Write a catchy, production-level ad headline (max 10 words).
    2. Write a short, persuasive tagline (max 15 words).

    Return ONLY a JSON object with this structure:
    {
        "headline": "string",
        "tagline": "string"
    }
    `;

    const ai = getAI(apiKey);
    const result = await ai.models.generateContent({
        model: TEXT_MODEL,
        contents: [
            { role: 'user', parts: [imagePart, { text: analysisPrompt }] }
        ]
    });

    const responseText = result.candidates?.[0]?.content?.parts?.[0]?.text || "{}";
    const cleanJson = responseText.replace(/```json|```/g, '').trim();
    let parsedData;
    
    try {
        parsedData = JSON.parse(cleanJson);
    } catch (e) {
        console.error("Failed to parse Gemini response:", responseText);
        // Fallback
        parsedData = {
            headline: "Experience Beauty",
            tagline: "Radiance redefined."
        };
    }

    // 2. Generate Image using Gemini 2.5 Flash (Nano Banana) with New Workflow
    if (!AD_STYLE_PROMPTS[style]) {
        console.warn(`Unknown ad style "${style}", falling back to Bold Modern`);
    }
    const stylePrompt = AD_STYLE_PROMPTS[style] || AD_STYLE_PROMPTS['Bold Modern'];
    
    const imageGenerationPrompt = `
    ${BASE_AD_PROMPT}

    ---
    INPUT CONTEXT:
    User Request: "${prompt}"
    Specific Text to Include: "${adText || `${parsedData.headline} - ${parsedData.tagline}`}"
    
    ---
    STYLE DEFINITION:
    ${stylePrompt}
    
    ---
    INSTRUCTIONS:
    Combine the INPUT CONTEXT with the STYLE DEFINITION to generate the final image.
    CRITICAL: The text MUST be rendered as a physical object in the scene (e.g. a neon sign, a poster on the wall, or 3D letters standing on the floor). It must be BEHIND the product. Do not overlay text digitally.
    Place the text strictly BEHIND the product, never overlapping.
    `;

    try {
        const response = await ai.models.generateContent({
            model: IMAGE_MODEL,
            contents: [
                { role: 'user', parts: [imagePart, { text: imageGenerationPrompt }] }
            ],
            config: {
                responseModalities: ['IMAGE'],
            }
        });

        const imageData = extractInlineImage(response);
        return {
            image: imageData,
            headline: parsedData.headline,
            tagline: parsedData.tagline
        };
    } catch (e) {
        console.error("Gemini generation failed:", e);
        throw new Error(`Failed to generate image with Gemini: ${e instanceof Error ? e.message : String(e)}`);
    }
};